services:
  authpipeline:
    container_name: authpipeline-agent
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/AnalysisPipeline
    restart: "no"
    volumes:
      - ./AnalysisPipeline/payer_sources:/app/AnalysisPipeline/payer_sources
      - ./AnalysisPipeline/outputs:/app/AnalysisPipeline/outputs
